# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    name: flask-app-deployment
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
      name: flask-app
  template:
    metadata:
      labels:
        type: front-end
        name: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: anisettygopi/flask:lms
        ports:
        - containerPort: 5000

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    name: flask-app-service
    tier: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32011
  selector:
    type: front-end
    name: flask-app